name: Build and deploy

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.

on:
  push:
    branches: [ master ]
  # Allow manually triggering deployment
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      uses: eskatos/gradle-command-action@v1.3.1
      with:
        arguments: clean build installDist
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true

    - name: Deploy
      uses: mojira/deploy@main
      with:
        azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        bastion_name: ${{ secrets.BASTION_NAME }}
        resource_group: ${{ secrets.RESOURCE_GROUP }}
        resource_id: ${{ secrets.RESOURCE_ID }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        username: risa
        artifact_paths: |
          build/install/risa/lib
          build/install/risa/bin
          risa.yml
          test/conf.txt
        artifact_destination: /home/risa/r-isa
        script: |
          /usr/bin/screen -ls | /bin/egrep 'Detached|Attached' | /usr/bin/cut -d. -f1 | /usr/bin/awk '{print $1}' | /usr/bin/xargs /bin/kill
          sleep 1
          cd r-isa
          /usr/bin/screen -d -m bash -c '/home/risa/r-isa/bin/risa; exec sh'
